### ISSUE TITLE
Outlook.com does not respect multiple class selector (without space)

### ISSUE THREAD

**Issue by nathankeenmelb** [hteumeuleu/email-bugs#106]
In this test ".first.second" is ignored by Outlook.com
```
<head>
    <style>
        .first.second {
            color:#ff0000;
        }
        .second {
               color:#00ff00;
        }
    </style>
</head>
<body>
<p class="first">One class</p>
<p class="first second">Too classy</p>
</body>
```
If there are multiple selectors separated by a comma, those will still work. 

Solution is to not use this construction (id's still work, or alternative classes by themselves).

**Comment by husseinalhammad** [comment]
I think this is the same bug as #61

**Comment by hteumeuleu** [comment]
Yes, it's the same. I'm closing this.
