### ISSUE TITLE
Outlook iOS app adding `display: table !important` inline

### ISSUE THREAD

**Issue by M-J-Robbins** [hteumeuleu/email-bugs#112]
Outlook on iOS is adding `display: table !important` inline to all table elements.

[Reported by Henrik Boy on EmailGeeks here](https://emailgeeks.slack.com/archives/C1Z733K1P/p1647270468840499)

I tested this on 4.2207.0 and it wasn't happening, Henrik had 4.2208.0 and was seeing the issues.  I've since updated to 4.2209.1 and I'm seeing it now too

```html
<style>
	.foo{
		background:red;
		display:none;
	}
</style>

<table class="foo">
	<tr>
		<td>test</td>
	</tr>
</table>
```

will become 
```html
<table class="foo" data-ogsb="" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-stroke-width: 0px; text-decoration: none; border-spacing: 0px; caret-color: rgb(225, 225, 225); color: rgb(225, 225, 225); font-family: -apple-system, HelveticaNeue; font-size: 20px; -webkit-text-size-adjust: 125%; background-color: rgb(234, 0, 0) !important; display: table !important;">
	<tbody>
		<tr>
			<td>test</td>
		</tr>
	</tbody>
</table>
```

I also tested setting `display:none` and `display:none !important` inline on a table and that didn't work either.

This means that you can no longer set `display:none` or any `display` value other than `table` on a table. 

A simple workaround from Steven Sayo is to wrap the table in a `div` and target that instead.

**Comment by M-J-Robbins** [comment]
I'm still using version 4.2209.1 but the issues appears to be fixed 🤷‍♀️

**Comment by lukepaperless** [comment]
Hi, I can't view the slack referenced above, but this issue seems to have arose again, which causes the issues shown here: 
https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-mobile-on-ios-styling-issue/b6c6e221-e062-47a3-a263-b4e4dee5e1e3

Outlook IOS Version: 4.2214.0

Did this ticket get closed because you found a workaround, or that the issue was resolved?
