### ISSUE TITLE
Orange email app not taking width in media queries

### ISSUE THREAD

**Issue by Frolipon** [hteumeuleu/email-bugs#116]
I have found a strange behavior in the Orange email app (only in the app, not in the webmail):

If you have a media queries specifying a new width, it won't be taken into account.
Example:

```
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml" xml:lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en">

<head>
	<title>Newsletter</title>
	<style type="text/css" title="template-stylesheet">
		
		@media only screen and (max-width:600px) {

			.displaynone {
				display: none !important;
			}
      .width100pc {
				width: 100% !important;
			}
			.displayblock {
				display: block !important;
			}
</style>
</head>

<body bgcolor="#F2F2F2" id="body" style="margin: 0px; padding: 0px; background-color: #F2F2F2;">
	<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" bgcolor="#F2F2F2" width="100%" style="margin: 0px auto;">
		<tr>
			<td align="center">
				<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin: 0px auto;width:600px;" bgcolor="#000000">
					<tr>
						<th class="displayblock width100pc" style="width:200px;font-size:40px;" bgcolor="#FF0000" >
							&nbsp;
						</th>
						<th class="displayblock width100pc" style="width:200px;font-size:40px;" bgcolor="#00FF00" >
							&nbsp;
						</th>
						<th class="displayblock width100pc" style="width:200px;font-size:40px;" bgcolor="#0000FF" >
							&nbsp;
						</th>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</body>

</html>
```

I tried several things:
- Change the CSS property of the class to a `background-color: #FFFF00 !important;` to make sure Orange read the class, and it works
- I tried to change the value from `%` to `px`, but it doesn't work
- I tried to add another class with `max-width: 100% !important;` but it doesn't work.

My best guess is that there is another CSS property from the Orange app overruling any change in the width by media queries.
I tried to add an ID on the `<table>` to see if by targeting I could get the width to work, but it does not work.
So far, I haven't found a work around…

**Comment by hteumeuleu** [comment]
Isn't this because Orange strips the `important` keyword? https://www.caniemail.com/features/css-important/
