### ISSUE TITLE
Outlook keeps only the first class in `class` attribute, ignoring everything else

### ISSUE THREAD

**Issue by e1himself** [hteumeuleu/email-bugs#117]
Stylesheet:

```html
<!--[if gte mso 9]>
<style type="text/css">
.red {
    color: red;
}
.large {
    font-size: 72px;
}
</style>
<![endif]-->
```

Markup:

```html
<div class="red">
    THIS SHOULD BE RED IN OUTLOOK
</div>
<div class="large">
    THIS SHOULD BE LARGE IN OUTLOOK
</div>
<div class="red large">
    THIS SHOULD BE RED AND LARGE IN OUTLOOK
</div>
<div class="large red">
    THIS SHOULD BE RED AND LARGE IN OUTLOOK
</div>
```

Result:

![Screenshot from 2022-07-13 17-27-56](https://user-images.githubusercontent.com/370680/178758388-27df5c70-d75d-483f-8f76-b8b91c9f40d2.png)

As far as I see, all versions of Outlook are affected. Including the newer ones.

**Comment by husseinalhammad** [comment]
I think this is is the same as #75

**Comment by e1himself** [comment]
Ah, you're right. I have searched if this was already reported, but somehow missed it. 

Thanks!
