### ISSUE TITLE
Current Streaks and Longest Streaks bugs on README.md

### ISSUE THREAD

**Issue by purnasth** [hteumeuleu/email-bugs#132]
![bug](https://github.com/hteumeuleu/email-bugs/assets/107195487/20075269-093b-478d-a6b5-078d0f211ab1)

My streaks up until yesterday were 18; I'm not sure how they got to 11 today when I checked. Please correct this problem; how is this even possible?

**Comment by jkupczak** [comment]
I think you might be lost my friend. This is a repository for email client bugs.
