### ISSUE TITLE
AOL incorrectly prefixes CSS animation @keyframes steps

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#14]
In its desktop webmail, AOL incorrectly prefixes every step inside a `@keyframes` declaration by `. aolReplacedBody`. The following example…

```html
<style type="text/css">
	@keyframes background900
	{
		0% { background-position:0 0; }
		100% { background-position:0 -900px; }
	}
</style>
<div style="width:480px; height:480px; background:#000 url(http://i.imgur.com/WItksSm.png) repeat-y; animation:background900 45s linear infinite;"></div>
```

… is transformed by  AOL into : 

```html
<style type="text/css">
	@keyframes background900
	{
		. aolReplacedBody  0% { background-position:0 0; }
		. aolReplacedBody  100% { background-position:0 -900px; }
	}
</style>
<div style="width:480px; height:480px; background:#000 url(http://i.imgur.com/WItksSm.png) repeat-y; animation:background900 45s linear infinite;"></div>
```

This is incorrect in CSS, and makes the animation void. Steps inside a `@keyframes` declaration should not be prefixed.

**Comment by hteumeuleu** [comment]
This bug was [reported to the AOL team on Twitter](https://twitter.com/hteumeuleu/status/710038750022254593) yesterday.

**Comment by mbeckerhh** [comment]
This is fixed now.

**Comment by hteumeuleu** [comment]
I just retested and confirm it works. This is awesome, thanks !
