### ISSUE TITLE
Outlook.com removes `<style>` tags in the `<head>`

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#141]
Last Friday, June 21st, was reported on Slack that Outlook.com (desktop webmail) was removing `<style>` tags. This seems to affect users worldwide but with a slow rollout. (I only started seeing this on Monday, 24th.) We don't know if this is a temporary issue or permanent feature.

In the meantime, it’s been found that only `<style>` tags in the `<head>` of an email were removed. So we can include `<style>` tags in the `<body>` and they'll work. If you need to go that route, make sure to duplicate your `<style>` tags as Gmail doesn't support them in the `<body>`. 

You can use Can I email’s `<style>` tag test to see how support is at the moment: https://www.caniemail.com/tests/html-style.html

![A screenshot of the test email in Outlook.com. Only style tags inside the body show with a green background.](https://github.com/hteumeuleu/email-bugs/assets/3451753/9aae632d-7d04-48ac-9ae1-ea50b4c426de)

**Comment by JayOram** [comment]
Could you do the 'hack' which uses <head> inside the body tag, so the styles work in Gmail?

e.g.

``` 
<html>
<body>
  <head>
    <style>
     ...
    </style>
  </head>
</body>
</html>
```

**Comment by NivenRanchhod** [comment]
@JayOram I thought the same and ran a test. That also works to remedy the issue.

**Comment by Dalinex** [comment]
Unfortunately for Yahoo that is not a solution. It has to stay in <head>. The rest of style can be in <body> and looking at tests on Gmail there is no problem, at least I don't see it on devices or in EOA.

**Comment by NivenRanchhod** [comment]
@Dalinex Which solution isn't working for you? Remi's shifting to the body tag or the wrapping in head tags and shifting to the body?
What issues are you seeing in Yahoo and which device? I ran Remi's test in Litmus and it looks fine to me on webmail, but maybe that isn't the right scenario for all tests.

**Comment by Dalinex** [comment]
This specific style is for Yahoo - and it is **only** for iPhone 13 - iOS 17.5.1 - when you have .png, in dark mode, Yahoo adds white background. If I move that style in <body> than .png gets white background again. If it stays after <head> than it looses white background. I tested on Email on Acid and other devices and desktops, are working fine.

<style>
@media screen yahoo and (max-width:413px) {
.yblack-bg {
.ydivdark[class=divdark] {
background-color: rgba(255,255,255,0.00);
}
}
.yfix{}
.yblack-bg {
background-color:rgba(255,255,255,0.00);
}
}
</style>
![code in body yahoo](https://github.com/hteumeuleu/email-bugs/assets/42481911/3e285ac0-930e-4a93-921e-75e29966ab23)

**Comment by NivenRanchhod** [comment]
@Dalinex What happens when you double up as Remi mentions?

**Comment by Dalinex** [comment]
I haven't tested that option since I saw that Yahoo style is holding OK in iPhone - iOS combo. 
But, if I put style after body - everything is working fine - all over all devices. 
Doubling would double the code and my emails are sometimes huge due to multiple tables and columns. 

But thing is that for now Outlook emails are ok in inbox - that is why I asked if Europe is showing this bug.

**Comment by NivenRanchhod** [comment]
Fair enough.
Litmus doesn't have Yahoo mobile app tests, so it would be great if you can test in EoA and report back on this ticket, so we know if the workarounds mentioned, work.

I'm in the UK and I'm seeing the bug. 
Litmus is also showing the issue in their screenshots for Office 365 and Outlook.com.

**Comment by Dalinex** [comment]
Email on Acid doesn't have mobile preview for Yahoo. The tests are done on real devices. This is screenshot of iPhone and Samsung - both combo. 
![iPhone13_iOS17_DM_Yahoo](https://github.com/hteumeuleu/email-bugs/assets/42481911/bc7a6137-720d-4061-b6ba-1e27f957948a)
![Samsung_A40_V11_DM_Yahoo](https://github.com/hteumeuleu/email-bugs/assets/42481911/bdca73a4-edeb-4c29-96c1-8a90f60c7d7b)

I still cant see any problems on EOA screenshots for any Outlook - so kind on stand by.

**Comment by wilbertheinen** [comment]
Outlook for Mac (16.85.1 (24051916)), which is using the same render engine as outlook.com, seems to still render correctly

**Comment by digicase** [comment]
@wilbertheinen I can confirm Outlook for Mac Version 16.86.2 (24062313) is also not exhibiting the issue. Outlook for web does.

I duplicated the `<style>` elements into the `<body>` tag and that fixed Outlook for web.

Hopefully Microsoft revert their changes. HTML code for email apps is bad enough without having to duplicate parts of it!

**Comment by iRyusa** [comment]
Is there any potential side effect on any other client when duplicating styles block in body ? 

Edit: I've tested a bit with few templates on MJML with big style block and couldn't find any on Email On Acid yet.

**Comment by thelefflaNA** [comment]
I can confirm on my end that I was able to repo this issue this week, but today it seems to have reverted back, anyone no longer seeing the issue?
Monday
![image (5)](https://github.com/hteumeuleu/email-bugs/assets/125772633/a87a0cc5-97d0-4735-9a3b-9306f8348210)

Friday
![image](https://github.com/hteumeuleu/email-bugs/assets/125772633/947bf13e-abc8-4d5a-bac4-b1a6cd38c8ee)

**Comment by ThiesPublishing** [comment]
Confirmed this was rolled back.

**Comment by Michele-VO** [comment]
We're still seeing the issue. Is this reverting back for everyone?

**Comment by NivenRanchhod** [comment]
It wasn't here for me in the UK when TheisPublishing stated it was reverted, but checking again today, all is back to normal.

**Comment by thelefflaNA** [comment]
> We're still seeing the issue. Is this reverting back for everyone?

If it was rolled out in batches, it might be the same in its reversions

**Comment by ThiesPublishing** [comment]
It was definitely rolled out in batches, so it makes sense it'd revert in batches as well. Be sure to clear your browser's cache.

**Comment by hteumeuleu** [comment]
I'm closing this as I feel like it's been rolled back globally now. But feel free to comment if that's not the case or if this comes back.

**Comment by Roye7777777** [comment]
On desktop outlook.com this problem is gone, but this problem still exists when opening outlook.com on touch devices (the 'mobile' version, not the app). There, I notice style tags are apparently still being stripped in the head, while leading the style in the body alive. 

1. desktop web outlook.com

<img width="737" alt="Scherm­afbeelding 2025-01-14 om 11 07 48" src="https://github.com/user-attachments/assets/d1b568bd-73dd-4003-8aaf-b72c2c662f25" />

2. mobile web outlook.com 

<img width="664" alt="Scherm­afbeelding 2025-01-14 om 11 08 26" src="https://github.com/user-attachments/assets/3fcf0471-20aa-479b-9d8a-390a9ad1d766" />

3. mobile iOS app outlook.com

![image](https://github.com/user-attachments/assets/27078631-4285-47e6-972e-46bdfb70aa96)

Used source (assuming limegreen in the head should be shown because this has a higher specificity):
```
<!DOCTYPE html>
<html lang="nl" dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
<head></head>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="x-apple-disable-message-reformatting">
    <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no">
    <meta name="color-scheme" content="light dark">
    <meta name="supported-color-schemes" content="light dark">
    <title>
        Mobile outlook.com test
    </title>
    <style type="text/css"></style>
    <style type="text/css">
      #bodyStyle .test{background:limegreen !important;}
    </style>
</head>
<body id="bodyStyle" style="margin:0px;padding:0px;background:#FFF;color:#000;" cz-shortcut-listen="true">
<style type="text/css">
    .test{background:tomato !important}
</style>
<div style="width:200px;height:200px;font-size: 16px;line-height:1.2;color:black;background:lightgrey" class="test">
    Test
</div>
</body>
</html>
```
