### ISSUE TITLE
Yahoo adds overflow-x/y:auto when using max-width/height

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#17]
Yahoo's desktop webmail seems to add the CSS property `overflow-x:auto;` when it sees the property `max-width` inline, and `overflow-y:auto;` when it sees the property `max-height`.

For example, the following code… 

``` html
<div style="max-width:50px; max-height:50px;>Lorem ipsum</div>
```

… will be transformed by Yahoo into : 

``` html
<div style="overflow-x:auto;max-width:50px;overflow-y:auto;max-height:50px;">Lorem ipsum</div>
```

---

A fix consists of adding an `overflow:visible` property. So the following code… 

``` html
<div style="max-width:50px; max-height:50px; overflow:visible;>Lorem ipsum</div>
```

… will be transformed by Yahoo into : 

``` html
<div style="overflow-x:auto;max-width:50px;overflow-y:auto;max-height:50px;overflow:visible;">Lorem ipsum</div>
```

However, this won't work on Internet Explorer because Yahoo also adds `-ms-` prefixed versions of the `overflow-` properties. So the latest example becomes on Internet Explorer : 

``` html
<div style="overflow:visible; -ms-overflow-x:auto; -ms-overflow-y:auto; max-height:50px; max-width:50px;">Lorem ipsum</div>
```

**Comment by teresapayne** [comment]
Has anyone found a fix to the -ms-overflow-x:auto styling? Yahoo in IE.
I've been able to find fixes for everything but that.

**Comment by lcjf** [comment]
I haven't found a "fix" (I tried camel casing, and alternating lower/uppcase etc.), but in my case, I put the max width values within my 'max-width' media query. I discovered that I only needed to apply the max width values for  the responsive version of my template.

If you can't do this then an alternative approach may be to set those values on the parent td, if that isn't possible then maybe replace your div with a table.

**Comment by danebest** [comment]
"overflow:visible!important;ms-overflow:visible!important;" immediately after your max-width, width, max-height, or height will fix the issue for Yahoo! webmail in IE. That said, the issue may be caused from competing widths or heights, which when cleaned up will avoid the issue altogether.

Cheers!

**Comment by revelt** [comment]
The following doesn't work:

    html {
      -ms-overflow-style: -ms-autohiding-scrollbar;
    }

[source](https://css-tricks.com/snippets/css/hide-scrollbar-in-edge-ie-1011/)

**Comment by revelt** [comment]
ms-overflow:visible!important;

@danebest your proposed `ms-overflow` doesn't work on both IE11/Edge+Yahoo webmail. I don't think such CSS style even exists; should it be `-ms-overflow-style` [[source](https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-overflow-style)]?

**Comment by hteumeuleu** [comment]
I just had this bug again. The solution suggested by @danebest to add `overflow:visible!important`at the end of my `style` worked for me for IE11. Adding `ms-overflow:visible!important;` is not necessary as it's filtered by Yahoo.

On a side note, this bug not longer seems to be present on the new Yahoo webmail UI.

**Comment by azzwho** [comment]
ms-overflow:visible!important; this is not working in yahoo . how do i get exact solution

**Comment by revelt** [comment]
_Yahoo_ on what browser exactly? I can't nail it on IE but my Crome/FF look fine.
Quick tip, check all the chain of tags up to the topmost, maybe it's parent tags or combo of them.
I remember I had to sprinkle the attribute everywhere.

**Comment by azzwho** [comment]
i checked it actually on IE11 yahoo have problem with div tag .. bug is
auto overflow .  and now it is okay .

**Comment by mgoggin** [comment]
I was bitten by this bug this last week while designing a new email campaign. Using `overflow:visible!important;-ms-overflow:visible!important` immediately following `max-width` fixed the issue in Yahoo on IE 10 and IE 11.

**Comment by revelt** [comment]
Ha! Apparently I didn't put the hyphen in front of my `ms-overflow` and that's why it didn't work... Thanks @mgoggin for sharing the snippet! It's such a face-palm case.. :)

**Comment by revelt** [comment]
hi all!

I can't recreate the issue any more, here's source in Chrome of the same `<div style="max-width:50px; max-height:50px;">Lorem ipsum</div>` (same code except closing double quote was missing in original Rémi's post so it was added):
![snip](https://user-images.githubusercontent.com/8344688/55233159-904dea80-521f-11e9-8c5f-ac732df6db1f.png)

**Overflows are not added any more!** Please check and confirm. I suspect this issue does not happen any more and we should close this.

**Comment by hteumeuleu** [comment]
I'm super late to the party but I also confirm that this no longer happens. I'm closing this bug now.
