### ISSUE TITLE
Gmail incorrectly prefixes HTML when turning images on

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#24]
On the desktop webmail of Gmail, when Gmail is set up to "_Ask before displaying external images_", a banner with "Images are not displayed" appears on top of an email with a link "Display images below".

![Gmail's "Images are not displayed" message banner](http://i.imgur.com/UPzK8VP.png)

If you click on the "Display images below" link, the HTML of your email will be reparsed but with a different prefix than the one used in the CSS. Thus, CSS rules no longer match the HTML, and emails might appear broken.

Here's an example.

```html
<!DOCTYPE html>
<html>
<head>
	<title>Gmail "Display Images Below" Bug</title>
	<style>
		p { background:#c44230; display:block; padding:1em; font: 1em/1.5 Open sans, sans-serif; color:#fff; }
		.foo { background:#39b54a; }
	</style>
</head>
<div>
	<p class="foo">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus atque nisi iure, iusto fugit cumque odio eos ipsa, recusandae molestiae hic magnam vero suscipit velit unde voluptates eaque non qui.
	</p>
	<img src="http://i.imgur.com/HhAfOct.gif" alt="This image is blocked." style="display:block; width:200px; height:100px;" />
</div>
</html>
```

![Example email with images blocked](http://i.imgur.com/YTH28gl.png)

On display, images are blocked. The HTML is turned into the following:

```html
<div id=":3a" class="a3s aXjCH m159215f7d36ee7fd">
	<u></u>
	<div>
		<p class="m_3567455155959655244foo">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus atque nisi iure, iusto fugit cumque odio eos ipsa, recusandae molestiae hic magnam vero suscipit velit unde voluptates eaque non qui.
		</p>
		<img alt="This image is blocked." style="display:block;width:200px;height:100px">
	</div>
</div>
````

And the styles are prefixed like this:

```html
div.m159215f7d36ee7fd p {
	background:#c44230;
	display:block;
	padding:1em;
	font:1em/1.5 Open sans,sans-serif;
	color:#fff
}

div.m159215f7d36ee7fd .m_3567455155959655244foo {
	background:#39b54a
}
```

If you click on the "Display images below" link, the HTML code is turned into the following: 

```html
<div id=":3a" class="a3s aXjCH m159215f7d36ee7fd">
	<u></u>
	<div>
		<p class="m_-8249599400804587256foo">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus atque nisi iure, iusto fugit cumque odio eos ipsa, recusandae molestiae hic magnam vero suscipit velit unde voluptates eaque non qui.
		</p>
		<img src="http://i.imgur.com/HhAfOct.gif" alt="This image is blocked." style="display:block;width:200px;height:100px" class="CToWUd">
	</div>
</div>
```

![Example email with images activated](http://i.imgur.com/sb5GhZM.png)

While the main `m159215f7d36ee7fd` prefix is kept the same, prefixes inside the email have changed. The class `foo`, first prefixed into `m_3567455155959655244foo` now becomes `m_-8249599400804587256foo`. The styles in the `<head>` haven't changed accordingly, so styles don't apply anymore.

Hat tip to Mark Robbins and Stig Morten Myre for sharing this bug on the Email Geeks Slack and on [this Campaign Monitor post](https://www.campaignmonitor.com/blog/email-marketing/2016/10/gmail-update-googles-rendering-refresh/).

**Comment by djsstorm** [comment]
Hi
There is a workaround solution for this bug?

**Comment by hteumeuleu** [comment]
Not really. You can try to target elements using tag selectors (like `table + table + table`), but that can be hard to pull off on a real life layout. Otherwise, make sure your main styles are inline.

**Comment by WebDevJoshB** [comment]
My suggestion is to continue using a combination of inline styles and internal styles. I use this method and have never had this issue. The other reason you should continue using inline CSS is because if your users open a non-gmail account in the Android gmail app (ex: yourname@outlook.com or yourname@hotmail.com), the internal styles are completely stripped. So if you don't have inline styles defined, your email will have no styling whatsoever.

**Comment by tdenk94** [comment]
I am currently using mailchimp to pass in an image, but I don't have access to that image element in the code (just the merge tag *|IMAGE|*) When this issue arises in Gmail, I can't access that image element. Any idea how to accomplish this?

`<style>
.share-img img{
	max-width: 60%;
    margin-bottom: 5px;
}
@media screen and (max-width: 480px){
	.share-img img{
    	max-width: 90%;
        margin-bottom: 5px;
     }
}   
</style>
<div class="share-img" style="text-align: center; width: 100%;">*|IMAGE|*</div>`

**Comment by hteumeuleu** [comment]
@tdenk94 I don't think there's a solution for your problem. Gmail will make invalid any style in a `<style>` tag in this case. The way to go is with inline styles. Try to see if Mailchimp doesn't have a way to include inline style in your case.

**Comment by WebDevJoshB** [comment]
@tdenk94 

I don't use MailChimp, but normally there should be an option to switch between a WYSIWYG text editor and HTML. Maybe this link will help?  https://kb.mailchimp.com/templates/code/where-to-edit-template-code

**Comment by jkupczak** [comment]
The original post mentions that this is an issue with the desktop version of Gmail. But I've seen this in the Gmail app for android as well. I can only assume it's the exact same issue. But I don't see why it would exist since Google does not need to prefix CSS at all in mobile because there isn't going to be any overlapping CSS like on desktop.

**Comment by hteumeuleu** [comment]
This bug appears to be fixed in [the new Gmail](https://blog.google/products/gmail/stay-composed-heres-quick-rundown-new-gmail/).
