### ISSUE TITLE
Apple Mail IOS 10 breaking letters

### ISSUE THREAD

**Issue by hotrush** [hteumeuleu/email-bugs#26]
Testing device: iphone 6s with Ios version: 10.2.1 and native mail app.

How letter looks on PC:
![1495464235199](https://cloud.githubusercontent.com/assets/1247004/26314328/54664aa8-3f16-11e7-8458-2708970d3fe8.jpg)
![1495464262119](https://cloud.githubusercontent.com/assets/1247004/26314327/546513ea-3f16-11e7-9739-a2335187d041.jpg)

How it looks on mobile:
![screenshot_2017-05-22-17-39-45-776_com google android gm](https://cloud.githubusercontent.com/assets/1247004/26314364/6e2e8856-3f16-11e7-99a9-40353c38335b.png)

How it looks on IOS 10 and apple mail app:
![1495464396857](https://cloud.githubusercontent.com/assets/1247004/26314434/a35a77f6-3f16-11e7-8d0f-2fda794749f8.jpg)
![1495464382427](https://cloud.githubusercontent.com/assets/1247004/26314435/a36006b2-3f16-11e7-8029-054b7d7b4da9.jpg)

It is pretty large (~50kb) and long mail, but it works well with all clients and devices except apple mail. Maybe someone met this problem and know any workaround?

**Comment by revelt** [comment]
Hi! Very probably something's wrong with the code. Would you be able to dump the sanitised HTML somewhere (like gist)? Alternatively, email me the raw source of it.

**Comment by hotrush** [comment]
Hi @revelt, thanks for your reply. I have created a gist with source html https://gist.github.com/hotrush/5f657a61ed811a3cb0bf6d387d3f2b8a
Also i think i can request for eml file if needed.

**Comment by hotrush** [comment]
@revelt and not sure for 100% if this matters, but all reported users using hotmail accounts

**Comment by revelt** [comment]
@hotrush strange, looks ok on Apple Mail @ iPhone7, gmail account:
![img_0289](https://cloud.githubusercontent.com/assets/8344688/26404320/6627d06c-4089-11e7-8088-ee569388208f.PNG)

**Comment by revelt** [comment]
@hotrush Hotmail.co.uk account, Apple Mail, iPhone7. All OK (not considering design&UX):

![img_0290](https://cloud.githubusercontent.com/assets/8344688/26404603/74e017ee-408a-11e7-8bc2-7ec0f6b8c43c.PNG)

**Comment by revelt** [comment]
@hotrush can you rule out that it is not a corporate firewall issue, because I've seen that before.

**Comment by hteumeuleu** [comment]
I'm closing this issue. It looks more like the problem comes from the email itself (or the server used to send the email) than Apple Mail.

**Comment by revelt** [comment]
+1
