### ISSUE TITLE
Outlook.com resets max-width of images inside tables

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#29]
As reported by Wassif A. on the #emailgeeks slack, [Outlook.com](https://outlook.live.com/mail/) has a new default style that resets the max-width property for images inside tables. Here's the incriminated rule :

```
._3z9ix0Ue99trWXkNz-xubm table img {
    max-width: none!important;
}
```

Here's a test email : 

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Outlook.com max-width reset</title>
</head>
<body>
	<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;">
		<tr>
			<td>
				<div style="max-width:200px; width:100%;">
					<p style="margin:0; padding:1em; color:#fff; background:#ff4136;">The image below shouldn't exceed 200px wide.</p>
				</div>
				<img src="https://i.imgur.com/l530ez3l.jpg" alt="" style="display:block; width:100%; max-width:200px;" width="2294"  />
			</td>
		</tr>
	</table>
</body>
</html>
```

A solution could be to add an `!important` inline on each image. Like this : 

```
<img src="https://i.imgur.com/l530ez3l.jpg" alt="" style="display:block; width:100%; max-width:200px!important;" width="2294"  />
```

**Comment by hteumeuleu** [comment]
Testing today, it looks like this was fixed. Anyone else confirms?

**Comment by revelt** [comment]
Just tested both cases on an old Hotmail inbox - without `!important` it goes full width, with it stays at 200. Confirmed.

@hteumeuleu Thanks for documenting this!
