### ISSUE TITLE
Yahoo removes rgba declarations for certain properties

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#37]
Yahoo removes `rgba` color declarations for certain CSS properties, like `border`, `text-shadow` or `outline`. The following code:

```html
<style>
	div {
		text-shadow:.1em .1em rgba(0,0,0,0.5);
		border:1px solid rgba(0,0,0,0.5);
		outline:1px solid rgba(0,0,0,0.5);
	}
</style>
```

…is transformed by Yahoo into:

```html
<style>
	div {
		text-shadow:.1em .1em;
		border:1px solid;
		outline:1px solid;
	}
</style>
```

This might be problematic because in CSS, if a `text-shadow` declaration doesn't have a color specified, it defaults to the `currentColor` CSS variable which matches the font color. This makes `text-shadow` unreliable in Yahoo with `rgba` colors.

![An example of a problematic text-shadow visible in Yahoo's desktop webmail.](https://user-images.githubusercontent.com/3451753/37458759-50850d9c-2846-11e8-8005-4a11ad2105d0.png)

For other properties (like `background-color` or `color`), Yahoo doesn't support `rgba` colors either, but it will strip the entire property.

**Comment by revelt** [comment]
👍 Confirms https://www.campaignmonitor.com/css/color-background/rgba-colors/

**Comment by hteumeuleu** [comment]
Just to make sure: the problem is not that much that Yahoo doesn't support `rgba`. The problem is that Yahoo changes the meaning of CSS declarations by filtering the `rgba` function. For the examples above, it would be better if Yahoo removed the property altogether instead of just removing the `rgba` function.

**Comment by revelt** [comment]
true

**Comment by husseinalhammad** [comment]
Yahoo doesn't strip `rgba()` any more:

![yahoo_rgba](https://user-images.githubusercontent.com/8544092/106376003-89a7d580-63aa-11eb-817c-67567c0240c8.png)

**Comment by hteumeuleu** [comment]
I confirm! Both in inline styles and embedded styles. Great news!
