### ISSUE TITLE
AOL and background-image in a <style> tag

### ISSUE THREAD

**Issue by iDerp69** [hteumeuleu/email-bugs#58]
https://github.com/hteumeuleu/email-bugs/issues/2

This issue appears to have resurfaced, pretty much verbatim as described in the previous thread. Our background images are not functioning properly in AOL, with only the "background=" html tag working. This isn't tenable, as Samsung's browser only reads the "background=" tag, so I'm left with a mobile and desktop mail client that are reading the same tag when I need different images delivered.

**Comment by hteumeuleu** [comment]
Could it be related to [this instead](https://github.com/hteumeuleu/email-bugs/issues/16#issuecomment-464795000)? AOL now uses Yahoo's parsing engine since july 2018, so every Yahoo bug now applies for AOL users as well.

**Comment by iDerp69** [comment]
It doesn't seem like it. I tried stripping out spaces before my !important tags and I'm not seeing improvement. Important to note that Yahoo displays my background image fine, but I can only get either Samsung or AOL to display it properly.

I may have misdiagnosed this somewhat. As recently as last Friday I got a test e-mail to have garbled <a href> in my <style>. But it does seem that Samsung and AOL only read whatever is inline. Attempts to override using anything in a <style> tag seems futile, !important or not.

**Comment by hteumeuleu** [comment]
Could you share a code example?

**Comment by M-J-Robbins** [comment]
Ah yeah we're seeing this too.

It's only on backgrounds images in embedded `<style>` tags, inline `style=""` backgrounds are working ok.

Sames code samples as before are showing same results - https://github.com/hteumeuleu/email-bugs/issues/2

**Comment by hteumeuleu** [comment]
Ha, I see it now. I'll close this issue and reopen the old one. Thank you both for your help.
