### ISSUE TITLE
Gmail messes up animated GIF compression

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#60]
I've seen several reports this week that Gmail messes up animated GIF compression. Consider the following code with an animated GIF (thanks to Thomas D. on Slack for providing a similar example) :

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Jeff.gif</title>
</head>
<body>
	<img src="https://i.imgur.com/46uC2Ny.gif" alt="" />
</body>
</html>
```
<details>
  <summary>View original image</summary>
  
![jeff.gif](https://user-images.githubusercontent.com/3451753/56805579-ce8ff700-6829-11e9-8d06-b36ebec98195.gif)
</details>

Here's how Gmail transforms it:

```html
<img src="https://ci4.googleusercontent.com/proxy/6dDrR2aRe8Pwb86S4hahsncaTiiSe9xKIxB1JDXPpuXYahR2jHDfKuEYCd4LLL6bi78=s0-d-e1-ft#https://i.imgur.com/46uC2Ny.gif" alt="" class="CToWUd a6T" tabindex="0">
```
<details>
  <summary>View buggy image</summary>
 
![buggy-jeff](https://user-images.githubusercontent.com/3451753/56805812-6ee61b80-682a-11e9-8fe0-00911da00dd9.gif)
</details>

The resulting image is cropping visuals around what seems to be based on the text from some of the frames of the animation. Looking at the file in Photoshop, it looks like the compression is using some kind of Coalesce algorithm to stack the frames. ([Read more about GIF compression here](https://imagemagick.org/Usage/anim_basics/#coalesce).)

![jeff-in-photoshop](https://user-images.githubusercontent.com/3451753/56806005-fc297000-682a-11e9-8c5a-7507f0352010.png)

**A solution** shared by Caleb M. on the #emailgeeks Slack is to duplicate all frames (and make them half long). So if you have four frames `ABCD` of each 1 second, you need to edit your GIF so it has eight frames `AABBCCDD` of each 0,5 second.

<details>
  <summary>View fixed image</summary>

![jeff-fixed](https://user-images.githubusercontent.com/3451753/56806110-46aaec80-682b-11e9-9c73-b9949e5c4590.gif)
</details>

_-- Attachments_
[PSD from the examples shared here](https://github.com/hteumeuleu/email-bugs/files/3121132/jeff.gif.zip)

**Comment by nittygitty** [comment]
Has anyone else been seeing a bug in Gmail where it seems to be showing the frames of a GIF slowly, or  not showing every frame? [https://i.imgur.com/bCBftTP.gif](url) (correct image on right, gmail on left)

**Comment by nittygitty** [comment]
The duplication of frames then halfing their length did not solve my issue.

**Comment by revelt** [comment]
@nittygitty Another consideration is the exact compression settings: interlacing, how many colours palette has and maybe presence/absence of embedded colour space (sRGB or whatever). Maybe your settings were different from that suggested recipe used?

**Comment by hteumeuleu** [comment]
@nittygitty Duplicating the frames does solve the problem. Here's a fixed version of your animation: https://i.imgur.com/jUTL0Cg.gif

I edited my initial post to make it clearer that each frames needs to be duplicated individually, not the entire animation.

**Comment by nittygitty** [comment]
@hteumeuleu that version you posted does seem to be working for me now, thanks!

**Comment by revelt** [comment]
we should contact somebody at Google

**Comment by hteumeuleu** [comment]
[I pinged their account on Twitter](https://twitter.com/HTeuMeuLeu/status/1121758299169460225), but this is probably the least efficient way to do it.

**Comment by jkupczak** [comment]
Do we know how old this issue is?

**Comment by hteumeuleu** [comment]
I have no idea. But given it was brought up on Slack three times in the past two days, I'd say this is very recent. There's no way no one this would have been unseen before now.

**Comment by abisse** [comment]
We found an other solution which seams to work (for now) with our email marketing solution (cheetah digital):
- send the gif by hangout
- copy the URI of the image created on the google servers
- use this link in our emails

It's far from being a 'good' solution, but it does the job for us until google find a fix.

We have open a ticket on the google support [here](https://support.google.com/mail/thread/5106925) (in french).

@hteumeuleu, with your solution, how do you deal with animation (when there are a lot of short frames) ?

**Comment by hteumeuleu** [comment]
@abisse : So far, I did by hand in Photoshop. I duplicate every frame by hand (by clicking the "new frame" icon on each frame). And then I set the timing for those two frames.

**Comment by hteumeuleu** [comment]
It looks like Gmail has fixed this bug as of this morning. Can anyone else confirm?

**Comment by abisse** [comment]
I confirm that Google has fixed this bug.
Thx for your help. ;)
