### ISSUE TITLE
Email still rendering incorrectly in Apple mail app

### ISSUE THREAD

**Issue by lizm75** [hteumeuleu/email-bugs#66]
I've implemented the suggestions found [here ](https://github.com/hteumeuleu/email-bugs/issues/18)
But I'm still seeing this in apple mail:
![IMG_6A66D94A6B65-1](https://user-images.githubusercontent.com/56234400/66274771-37e74d80-e83f-11e9-88e5-0b4faaa79ecc.jpeg)
Here is the code:
[newsletter Test.docx](https://github.com/hteumeuleu/email-bugs/files/3694793/newsletter.Test.docx)

**Comment by hteumeuleu** [comment]
I'm not sure this is an email client bug. You seem to have a few tables defined with a fixed width that is not redefined in responsive (ie missing your `resizetofull` class):

```<table align="left" border="0" cellpadding="0" cellspacing="0" class="w200 padL0" width="415">```

**Comment by lizm75** [comment]
what would the correction look like?
