### ISSUE TITLE
Outlook.com turns `body` into `div` in CSS selectors

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#88]
Outlook.com turns `body` into `div` in CSS selectors. For example, a `body { background:red; }` is turned into `.rps_c988 div { background:red; }`. This can cause huge problems because a style supposedly targeted only for the unique `body` element is now applied to any `div` elements inside the rest of the HTML email. Microsoft should have used a child combinator (like `.rps_c988 > div`) instead of a descendant combinator. The best solution for now is to avoid using the `body` selector.

This must be a very recent change since I've seen a lot of people reporting problems about it in the last three days.

Here's a full example. The following code…

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Outlook.com turns body into div</title>
  <style>
    body { color:#fff; background: red; }
    body a { color:#fff; background: green; }
    body p { color:#fff; background: blue; }
    body div { color:#fff; background: yellow; }
  </style>
</head>
<body>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. 
</body>
</html>
```

…is transformed by Outlook.com into:

```html
<div><style>
<!--
.rps_c988 div
	{color:#fff;
	background:red}
.rps_c988 div a
	{color:#fff;
	background:green}
.rps_c988 div p
	{color:#fff;
	background:blue}
.rps_c988 div div
	{color:#fff;
	background:yellow}
-->
</style><div class="rps_c988"><div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi aliquid velit eligendi, dolor totam facilis at tenetur dolorum, nobis ab nostrum fugit ratione quaerat repellendus blanditiis, nulla neque eum obcaecati. </div></div></div>
```

**Comment by M-J-Robbins** [comment]
Quick note about how recent the change is.  On my account the change was not present on Monday 8th February nut others were seeing it. Then on Tuesday 9th February it was present on my account.

**Comment by peterc** [comment]
I have been debugging what seems to be a related issue today. Our subscribers were reporting that if they hovered over our email, it disappeared! I was directed to this report which I didn't think was related at first, but now I do. I have created the smallest possible example with all the elements needed to create such a "disappear on hover" email and I think the BODY CSS issue you're talking about is related:

```
<head>
  <style>
  body {
    width: 100%; height: 100%;
    background-color: white;
  }
  </style>
  </head>
  <body>
  <table align="center">
    <tr><td>
        <div style="padding-left: 14px">
          This will disappear on hover in Outlook.com.
        </div>
    </td></tr>
  </table>
  </body>
</html>
```

**Comment by revelt** [comment]
^ that example above with disappearing — confirmed. Tested on hotmail x firefox x macos. On the side note, the `div` is causing the problem. If you remove `div` there are no issues. For the record, the "old school" practice is exactly that — avoid using `div` — two cases pop to my head where I'd use `div`: 1. linking surfaces like nested tables (like British Airways does, see their newsletter); 2. for mobile layouts, like hiding or showing content. 

The "old school" way would be:

```html
<html>
<head>
  <style>
  body {
    width: 100%; height: 100%;
    background-color: white;
  }
  </style>
  </head>
  <body>
  <table align="center">
    <tr><td style="padding-left: 14px">
          This will disappear on hover in Outlook.com.
    </td></tr>
  </table>
  </body>
</html>
```

There is a sibling `<td>` padding bug which might be the reason why you're putting padding on separate div. Basically, you can't use different vertical padding on sibling `<td>` — solution is to nest.

Also, Peter's example above doesn't seem to be related to this issue ticket. Maybe we should create separate one, for disappearing `div`?

**Comment by hteumeuleu** [comment]
@peterc Wow, this is a fun one! The problem is indeed related. And it's not actually caused by divs in the code (and I really want to emphasize this: divs are perfectly fine to use in HTML emails). What's happening is that the original email is bigger than the "viewport" size in Outlook.com (the zone where the email is displayed). And so this triggers Outlook.com zoom feature, which adds a bunch of divs to the email.

```
<div class="_1nC-FSfxis9BCt3z-FF2DU" style="background-color: rgb(51, 51, 51) !important;" data-ogsb=""><button type="button" class="ms-Button ms-Button--icon _3klEWn_NpZR-PsWYhCiZ3_ root-58" title="Show original size" aria-label="Show original size" data-is-focusable="true" style="color: rgb(220, 220, 220) !important; background-color: rgb(51, 51, 51) !important;" data-ogsc="" data-ogsb=""><span class="ms-Button-flexContainer flexContainer-45" data-automationid="splitbuttonprimary"><i data-icon-name="FullScreen" role="presentation" aria-hidden="true" class="ms-Icon root-32 css-52 ms-Button-icon icon-47" style="font-family: &quot;controlIcons&quot;;"></i></span></button></div>
```

When you move your cursor over these divs, normally only the zoom button appears. But because we now have `body` styles applied to all divs, that include those zoom divs as well. So technically, your email doesn't disappear. But the zoom button container gets overlayed on top of your entire email, thus covering your email and making it not visible.

You can reproduce this bug without having any divs in your code but simply by having an element larger than Outlook.com's "email viewport". I used the following:

```html
<html>
<head>
  <style>
  body {
    width: 100%; height: 100%;
    background-color: white;
  }
  </style>
  </head>
  <body>
  <table style="width:1920px">
    <tr><td>
          This will disappear on hover in Outlook.com.
    </td></tr>
  </table>
  </body>
</html>
```

**Comment by fernamp** [comment]
I know this does not need to be your solution but, my two cents:

```
div:first-of-type div {
    background-color: transparent;
}

```
But that is for me cause we use tables in our mails and the divs are just replacement for the <p>aragraphs.
So, the CSS finds the obvious `.rps_c988` in the code and then the first child/sibling of its type (div) that was previously the body. The put a transparent background colour in every div inside the ex-body.

**Comment by husseinalhammad** [comment]
It looks like there has been an update in version `20210208002.03`, which now uses the child combinator selector `.rps_f331 > div {}` instead of the descendant combinator `.rps_f331 div {}`.

**Comment by hteumeuleu** [comment]
This is good news! Looks like I don't have it yet (also on version `20210208002.03`). This is likely just rolling out.

**Comment by hteumeuleu** [comment]
I confirm that I see the fix now.

**Comment by fernamp** [comment]
Mixed then:
<meta name="scriptVer" content="20210208002.03">

I still see the original code:
![image](https://user-images.githubusercontent.com/742912/108036114-1a7fe180-7038-11eb-8a92-48e48313b4de.png)

**Comment by hteumeuleu** [comment]
I got confirmation from a contact on the Outlook team that the rollout for the fix should be done now. I'm closing this now.
